name = "WeakDepHelpers"
uuid = "7869a13a-7328-4bcf-a489-0f4bb64497c7"
version = "0.1.0"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]

[deps]
JuliaSyntaxHighlighting = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
JuliaSyntaxHighlighting = "1.12"
StyledStrings = "1.11"
julia = "1.12"
